# -*- coding: utf-8 -*-
"""Pencari Informasi Suku Adat Indonesia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAPl4ykPMZ8g6b5xivuY_vjP1Bgj9yok
"""

!pip install wikipedia-api

!pip install wikipedia

import wikipedia
from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok
import requests

app = Flask(__name__)
CORS(app)

# KONFIGURASI
SERPER_API_KEY = "007cd85dc32460e4870ca5836fc8bb5c2bcfb879"
ngrok.set_auth_token("38azxuMCsQR3YkZU37HPrtE78b1_25UmvDb9wEr7vYdgrxgnS")

# Set bahasa ke Indonesia
wikipedia.set_lang("id")

def get_wiki_description(suku_name):
    # Bersihkan input
    query = suku_name.strip().title()

    # Daftar urutan pencarian
    search_attempts = [f"Suku {query}", query, f"{query} (suku bangsa)"]

    for attempt in search_attempts:
        try:
            # Mengambil ringkasan (summary) maksimal 3 kalimat
            summary = wikipedia.summary(attempt, sentences=3)
            return summary
        except wikipedia.exceptions.DisambiguationError as e:
            # Jika ambigu, coba ambil opsi pertama dari Wikipedia
            try:
                return wikipedia.summary(e.options[0], sentences=3)
            except: continue
        except wikipedia.exceptions.PageError:
            continue
        except:
            continue

    return f"Deskripsi untuk Suku {query} tidak ditemukan di database Wikipedia Indonesia."

def get_google_image(query):
    try:
        url = "https://google.serper.dev/images"
        payload = {"q": query, "num": 1}
        headers = {'X-API-KEY': SERPER_API_KEY, 'Content-Type': 'application/json'}
        response = requests.post(url, headers=headers, json=payload, timeout=5)
        data = response.json()
        return data['images'][0]['imageUrl'] if data.get('images') else ""
    except:
        return ""

@app.route('/translate', methods=['POST'])
def get_suku_info():
    data = request.get_json(force=True)
    suku = data.get('query', '').strip().title()

    deskripsi = get_wiki_description(suku)
    foto_orang = get_google_image(f"pakaian adat {suku}")
    foto_rumah = get_google_image(f"rumah adat {suku}")

    return jsonify({
        "deskripsi": deskripsi,
        "foto_orang": foto_orang,
        "foto_rumah": foto_rumah
    })

# Jalankan Server
try:
    public_url = ngrok.connect(5000)
    print(f"\nURL AKTIF: {public_url}/translate\n")
    app.run(port=5000)
except:
    ngrok.kill()