# -*- coding: utf-8 -*-
"""Pencari Informasi Suku Adat Indonesia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAPl4ykPMZ8g6b5xivuY_vjP1Bgj9yok
"""

!pip install wikipedia-api

!pip install wikipedia

"""
Backend Server untuk Aplikasi Pencari Suku Indonesia
Struktur: Flask + Wikipedia API + Serper Image API
Catatan: Isi API Key di bawah ini sebelum menjalankan server.
"""

import wikipedia
import requests
from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok

app = Flask(__name__)
CORS(app)

# --- KONFIGURASI API (WAJIB DIISI) ---
# Dapatkan API Key di https://serper.dev
SERPER_API_KEY = "MASUKKAN_API_KEY_SERPER_ANDA"

# Dapatkan Token di https://dashboard.ngrok.com
NGROK_TOKEN = "MASUKKAN_TOKEN_NGROK_ANDA"

ngrok.set_auth_token(NGROK_TOKEN)
wikipedia.set_lang("id")

def get_wiki_description(suku_name):
    """Mengambil ringkasan teks dari Wikipedia Indonesia secara cerdas"""
    query = suku_name.strip().title()
    search_attempts = [f"Suku {query}", query, f"{query} (suku bangsa)"]

    for attempt in search_attempts:
        try:
            # Mengambil 3 kalimat pertama
            return wikipedia.summary(attempt, sentences=3)
        except:
            continue
    return f"Deskripsi untuk Suku {query} tidak ditemukan di Wikipedia."

def get_google_image(query):
    """Mencari link gambar melalui Serper API"""
    try:
        url = "https://google.serper.dev/images"
        payload = {"q": query, "num": 1}
        headers = {
            'X-API-KEY': SERPER_API_KEY,
            'Content-Type': 'application/json'
        }
        response = requests.post(url, headers=headers, json=payload, timeout=5)
        data = response.json()
        return data['images'][0]['imageUrl'] if data.get('images') else ""
    except:
        return ""

@app.route('/translate', methods=['POST'])
def handle_request():
    """Endpoint utama untuk komunikasi dengan MIT App Inventor"""
    try:
        data = request.get_json(force=True)
        suku = data.get('query', '').strip().title()

        return jsonify({
            "deskripsi": get_wiki_description(suku),
            "foto_orang": get_google_image(f"pakaian adat {suku}"),
            "foto_rumah": get_google_image(f"rumah adat {suku}")
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    # Membuka tunnel Ngrok
    public_url = ngrok.connect(5000)
    print(f"\n--- SERVER BERHASIL DIJALANKAN ---")
    print(f"Salin link ini ke Web1.Url di App Inventor:")
    print(f"{public_url}/translate")
    print(f"------------------------------------\n")
    app.run(port=5000)